locations:
  - Montevideo
  - Canelones
  - Ciudad de la Costa
  - Las Piedras
  - Maldonado
  - Punta del Este
  - Piriápolis
  - Colonia del Sacramento
  - Carmelo
  - Salto
  - Paysandú
  - Rivera
  - Melo
  - Rocha
  - La Paloma
  - Minas
  - Durazno
  - Mercedes
  - San José de Mayo
  - Florida
  - Trinidad
  - Tacuarembó
  - Artigas
